# Generated by Django 3.2.9 on 2021-11-03 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='versioningapp.repository'),
            preserve_default=False,
        ),
    ]
