# Generated by Django 3.2.9 on 2021-11-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0002_branch_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
