# Generated by Django 3.2.9 on 2021-11-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0004_auto_20211104_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_directory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='versioningapp.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='sub_directories',
            field=models.ManyToManyField(blank=True, related_name='_versioningapp_folder_sub_directories_+', to='versioningapp.Folder'),
        ),
    ]
