# Generated by Django 3.1.5 on 2021-11-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0005_auto_20211105_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='child_branchs',
            field=models.ManyToManyField(blank=True, related_name='_branch_child_branchs_+', to='versioningapp.Branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='commits',
            field=models.ManyToManyField(blank=True, to='versioningapp.Commit'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='files',
            field=models.ManyToManyField(blank=True, to='versioningapp.File'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='folders',
            field=models.ManyToManyField(blank=True, to='versioningapp.Folder'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='versioningapp.branch'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, to='versioningapp.File'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branches',
            field=models.ManyToManyField(blank=True, to='versioningapp.Branch'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
