# Generated by Django 3.1.5 on 2021-11-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0006_auto_20211105_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='child_branchs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_branch_child_branchs_+', to='versioningapp.Branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='commits',
            field=models.ManyToManyField(blank=True, null=True, to='versioningapp.Commit'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='versioningapp.File'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='folders',
            field=models.ManyToManyField(blank=True, null=True, to='versioningapp.Folder'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='versioningapp.branch'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='versioningapp.File'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='versioningapp.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='sub_directories',
            field=models.ManyToManyField(blank=True, null=True, related_name='_folder_sub_directories_+', to='versioningapp.Folder'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, to='versioningapp.Branch'),
        ),
    ]
