# Generated by Django 3.1.5 on 2021-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0007_auto_20211105_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='child_branchs',
            field=models.ManyToManyField(blank=True, related_name='_branch_child_branchs_+', to='versioningapp.Branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='commits',
            field=models.ManyToManyField(blank=True, to='versioningapp.Commit'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='files',
            field=models.ManyToManyField(blank=True, to='versioningapp.File'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='folders',
            field=models.ManyToManyField(blank=True, to='versioningapp.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, to='versioningapp.File'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='sub_directories',
            field=models.ManyToManyField(blank=True, related_name='_folder_sub_directories_+', to='versioningapp.Folder'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branches',
            field=models.ManyToManyField(blank=True, to='versioningapp.Branch'),
        ),
    ]
