# Generated by Django 3.1.5 on 2021-11-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractivityapp', '0003_auto_20211107_1346'),
        ('versioningapp', '0008_auto_20211105_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='autor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_commits', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commit', to='useractivityapp.Comment'),
        ),
        migrations.AddField(
            model_name='repository',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='action_of_repositorys', to='useractivityapp.Action'),
        ),
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_repositorys', to=settings.AUTH_USER_MODEL),
        ),
    ]
