# Generated by Django 3.2.9 on 2021-11-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0010_auto_20211107_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='branches',
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='versioningapp.repository'),
            preserve_default=False,
        ),
    ]
