# Generated by Django 3.2.9 on 2021-11-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0011_auto_20211110_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_branch', to='versioningapp.branch'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
