# Generated by Django 3.2.9 on 2021-11-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0014_rename_repository_branch_repository_aaaaaaaaaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='repository_aaaaaaaaaa',
            new_name='repository',
        ),
    ]
