# Generated by Django 3.2.9 on 2021-11-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0015_rename_repository_aaaaaaaaaa_branch_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositoryBranch', to='versioningapp.repository'),
        ),
    ]
