# Generated by Django 3.2.9 on 2021-11-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0018_collaboration_collaborationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositoryCollaborations', to='versioningapp.repository'),
        ),
    ]
