# Generated by Django 3.1 on 2021-11-24 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versioningapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractivityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('is_opened', models.BooleanField(default=False)),
                ('assigness', models.ManyToManyField(blank=True, related_name='issue_assigned_to_me', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_created', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='issue', to='useractivityapp.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('description', models.CharField(max_length=200)),
                ('issues', models.ManyToManyField(blank=True, to='progresstrackapp.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able_to_merge', models.BooleanField(default=False)),
                ('is_merged', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('title', models.CharField(max_length=200)),
                ('assigness', models.ManyToManyField(blank=True, related_name='pull_request_assigned_to_me', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('base_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_branchs', to='versioningapp.branch')),
                ('comments', models.ManyToManyField(blank=True, related_name='pull_request', to='useractivityapp.Comment')),
                ('compare_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_branch', to='versioningapp.branch')),
                ('issues', models.ManyToManyField(blank=True, to='progresstrackapp.Issue')),
                ('labels', models.ManyToManyField(blank=True, to='progresstrackapp.Label')),
                ('milestones', models.ManyToManyField(blank=True, to='progresstrackapp.Milestone')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='versioningapp.repository')),
                ('reviewes', models.ManyToManyField(blank=True, related_name='wated_review_from_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='progresstrackapp.Label'),
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='versioningapp.repository'),
        ),
    ]
