# Generated by Django 3.1.5 on 2021-11-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versioningapp', '0008_auto_20211105_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('is_opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('description', models.CharField(max_length=200)),
                ('issues', models.ManyToManyField(blank=True, to='progresstrackapp.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_able_to_merge', models.BooleanField(default=False)),
                ('is_merged', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('title', models.CharField(max_length=200)),
                ('base_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_branchs', to='versioningapp.branch')),
                ('compare_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_branchs', to='versioningapp.branch')),
                ('issues', models.ManyToManyField(blank=True, to='progresstrackapp.Issue')),
                ('labels', models.ManyToManyField(blank=True, to='progresstrackapp.Label')),
                ('milestones', models.ManyToManyField(blank=True, to='progresstrackapp.Milestone')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='progresstrackapp.Label'),
        ),
    ]
