# Generated by Django 3.1.5 on 2021-11-07 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progresstrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigness',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
