# Generated by Django 3.1.5 on 2021-11-07 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progresstrackapp', '0002_issue_assigness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='assigness',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='reviewes',
            field=models.ManyToManyField(blank=True, related_name='wated_review_from_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
