# Generated by Django 3.1.5 on 2021-11-07 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useractivityapp', '0002_auto_20211105_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versioningapp', '0008_auto_20211105_1727'),
        ('progresstrackapp', '0003_auto_20211107_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='issue', to='useractivityapp.Comment'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='pull_request', to='useractivityapp.Comment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigness',
            field=models.ManyToManyField(blank=True, related_name='issue_assigned_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='assigness',
            field=models.ManyToManyField(blank=True, related_name='pull_request_assigned_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='compare_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_branch', to='versioningapp.branch'),
        ),
    ]
