# Generated by Django 3.1.5 on 2021-11-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0008_auto_20211105_1727'),
        ('progresstrackapp', '0004_auto_20211107_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='versioningapp.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='versioningapp.repository'),
            preserve_default=False,
        ),
    ]
