# Generated by Django 3.1.5 on 2021-11-07 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractivityapp', '0002_auto_20211105_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='action_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_created', to='auth.user'),
            preserve_default=False,
        ),
    ]
