# Generated by Django 3.1.5 on 2021-11-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractivityapp', '0003_auto_20211107_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reactions_created', to='auth.user'),
            preserve_default=False,
        ),
    ]
