# Generated by Django 3.1.5 on 2021-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivityapp', '0004_reaction_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reaction',
        ),
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.ManyToManyField(blank=True, related_name='comment', to='useractivityapp.Reaction'),
        ),
    ]
