# Generated by Django 3.2.9 on 2021-11-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivityapp', '0006_auto_20211107_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='path_to_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
