# Generated by Django 3.2.9 on 2021-11-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractivityapp', '0007_alter_actiontype_path_to_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontype',
            name='path_to_icon',
        ),
    ]
