# Generated by Django 3.2.9 on 2021-11-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0020_collaboratordto'),
        ('useractivityapp', '0008_remove_actiontype_path_to_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='type',
            new_name='action_type',
        ),
        migrations.RemoveField(
            model_name='reactiontype',
            name='path_to_icon',
        ),
        migrations.AddField(
            model_name='action',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repositoryActions', to='versioningapp.repository'),
            preserve_default=False,
        ),
    ]
