# Generated by Django 3.2.9 on 2021-11-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivityapp', '0009_auto_20211122_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=200),
        ),
    ]
