# Generated by Django 3.2.9 on 2021-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivityapp', '0012_alter_action_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('author', 'repository', 'action_type'), name='unique_action_constraint'),
        ),
    ]
