# Generated by Django 3.2.9 on 2021-11-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioningapp', '0020_collaboratordto'),
        ('useractivityapp', '0013_action_unique_action_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='new_forked_repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actionNewForkedRepository', to='versioningapp.repository'),
        ),
    ]
